### PR TITLE
Upgrade Serverless to 1.65.0

### PR DESCRIPTION
**Pull request by mt-dfcowell**
SO OLD!!! 😱

### CODE REVIEW

**Comment by mt-sergio** [comment]
@mt-dfcowell 
1. we don't merge ourselves our PRs
2. this repository is deprecated and should never be used. We made a PR with our feature (by that time) to the master branch and got accepted. In any case, that doesn't work like that any more, so please, any repository that is using THIS repository, upgrade it 🙇

**Comment by mt-sergio** [comment]
https://github.com/moneytree/serverless/releases

**Comment by mt-dfcowell** [comment]
@mt-sergio 

1. Noted! Thought this case may be an exception since it was only merging upstream. I'll keep this in mind for the future. 🙇‍♂️
2. This is for my work on https://github.com/moneytree/mt-utility-lambdas which uses that feature in its CI script. I'm a bit wary of changing how it works, since I'm not sure what might break in AWS if I change how `restartHerokuDynos` is deployed.
3. Please put a deprecation notice in this repo's description so that other newcomers know that it's deprecated!

**Comment by mt-sergio** [comment]
Well, `restartHerokuDynos` is a pretty special piece in our environment as it helped a lot to recover from incidents. I think it had some custom permissions from Ross, so we kind of `denied` access to everybody.
My suggestion is that if you are not sure or consider newcomer to a project, start asking questions and waiting feedback from some peer (point number 1).
I love you taking care of that project, while I understand it's challenging. Empathize with the pressure we had in that moment :D 
I will add the "deprecated" as it's the first time to check the repository in years ;)

**Comment by makdad** [comment]
Glad to know we contributed successfully to Open Source.

**Pull request merged**
